main/urls.py
from django.urls import path
from django.contrib import admin
from .views import *

from django.conf.urls.static import static
from django.conf import settings

app_name='main'

urlpatterns = [
    path('admin/', admin.site.urls),
    # 웹사이트의 첫화면은 index 페이지이다 + URL이름은 index이다
    path('', index, name='index'),
    # URL:80/blog에 접속하면 blog 페이지 + URL이름은 blog이다
    path('blog/', blog, name='blog'),
    # URL:80/blog/숫자로 접속하면 게시글-세부페이지(posting)
    path('blog/<int:pk>/',posting, name="posting"),
    path('blog/new_post/', new_post),
    path('blog/<int:pk>/remove/', remove_post),
    path("signup/", signup, name="signup"),
    path("login/", user_login, name="login"),
    path("logout/", user_logout, name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/templates/main/blog.html
<html>
    <head>
        <title>Blog List</title>
    </head>
    <body>
        <button><a href="new_post/">글쓰기</a></button>
        <button><a href="/">메인화면</a></button>
        <table>
        {% for list in postlist %}
            <ul>
                <li><a href="{{list.pk}}/">{{list.postname}}</a></li>
            </ul>
        {% endfor %}
        </table>
    </body>
</html>

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'main:blog' %}">게시판</a>

{% if user.is_authenticated %}
    <p>환영합니다, {{ user.username }}님!</p>
    <a href="{% url 'main:logout' %}">로그아웃</a>
{% else %}
    <a href="{% url 'main:login' %}">로그인</a>
    <a href="{% url 'main:signup' %}">회원가입</a>
{% endif %}
</body>
</html>

main/templates/main/login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>로그인</title>
</head>
<body>
    <h2>로그인</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="username">아이디</label>
        <input type="text" id="username" name="username" required><br><br>

        <label for="password">비밀번호</label>
        <input type="password" id="password" name="password" required><br><br>

        <input type="submit" value="로그인">
    </form>

    {% for message in messages %}
        <p style="color: red;">{{ message }}</p>
    {% endfor %}
</body>
</html>

main/templates/main/new_post.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>글쓰기 페이지</title>
</head>
<body>
    <h1>글쓰기 페이지</h1>

    <form method="POST" enctype="multipart/form-data">  <!-- 🔹 중요: enctype 추가 -->
        {% csrf_token %}

        <label for="postname">제목</label><br>
        <input type="text" id="postname" name="postname" required><br><br>

        <label for="contents">내용</label><br>
        <textarea id="contents" rows="10" cols="50" name="contents" required></textarea><br><br>

        <label for="mainphoto">사진 업로드</label><br>
        <input type="file" id="mainphoto" name="mainphoto"><br><br>

        <input type="submit" value="글쓰기">
    </form>
</body>
</html>

main/templates/main/posting.html
<html>
    <head>
        <title>Posting!</title>
    </head>
    <body>
        <h1>{{post.postname}}</h1>
        <p>작성자: {{post.author}}</p>
        <p>{{post.contents}}</p>
        {% if post.mainphoto %}
            <img src = "{{ post.mainphoto.url }}" alt="" height="600">
            <br>
        {% endif %}
        <a href="/blog/">목록</a>
    </body>
</html>

main/templates/main/remove_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 삭제</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h3>{{ Post.postname }} - 삭제하기</h3>
        <button>삭제</button>
    </form>
</body>
</html>

main/templates/main/signup.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>회원가입</title>
</head>
<body>
    <h2>회원가입</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="username">아이디</label>
        <input type="text" id="username" name="username" required><br><br>

        <label for="password1">비밀번호</label>
        <input type="password" id="password1" name="password1" required><br><br>

        <label for="password2">비밀번호 확인</label>
        <input type="password" id="password2" name="password2" required><br><br>

        <input type="submit" value="회원가입">
    </form>

    {% for message in messages %}
        <p style="color: red;">{{ message }}</p>
    {% endfor %}
</body>
</html>